name: freestyle-job
on:
  workflow_dispatch:
env:
#   # TimestamperBuildWrapper was not converted because the behavior is available by default in GitHub Actions and/or it is not configurable
#   # This item has no matching transformer
#   hudson.plugins.sonar.SonarBuildWrapper:
#     plugin: sonar@2.15
#     credentialsId: sonar
#     envOnly: 'false'
jobs:
  build:
    runs-on:
      - self-hosted
      - slave
    steps:
    - name: clean workspace
      shell: bash
      run: rm -rf ${{ github.workspace }}/*
    - name: checkout
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0
    - name: run command
      shell: bash
      run: |-
        echo $PWD
        mkdir test
    - name: Set up JDK 1.11
      uses: actions/setup-java@v3.12.0
      with:
        distribution: zulu
        java-version: '1.11'
        settings-path: "${{ github.workspace }}"
    - name: Run maven
      run: mvn -f pom.xml -B clean verify
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.9
      env:
        SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        SONARCLOUD_URL: "${{ secrets.SONAR_URL }}"
      with:
        args: |
          #WARNING: projectKey is a required field, ensure it is configured here or in your project file
          -Dsonar.projectKey='<<INSERT KEY HERE>>'/`
          -Dsonar.host.url='${{ secrets.SONAR_URL }}'/`
          -Dsonar.login=${{ env.SONAR_TOKEN }}/`
