name: declarative
on:
  push:
    paths: "*"
  schedule:
  - cron: "*/50 * * * *"
jobs:
  Example:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: echo message
      run: echo Hello World
